default: &default
  adapter: postgresql
  pool: 5
  username: root
  password: 
  encoding: unicode

development:
  <<: *default
  database: business_utility_api_development

test:
  <<: *default
  database: business_utility_api_test

production:
  <<: *default
  database: business_utility_api_production

